spring:
  application:
    name: swapi-integration-service


  cloud:
    openfeign:
      client:
        config:
          swapiClient:
            url: https://swapi.dev
  cache:
    type: caffeine

api:
  format:
      people-api:
        dateFormat: dd-MM-yyyy
        massFormat: "%s kg"
        heightFormat: "%s meters"

